#!/bin/bash

if [ ! -z $1 ];
then
target=$1
else
exit
fi
echo -e "\nARP Scanning..."
arp-scan -q $1 |grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | tee /tmp/arp-scan
echo -e "\nScan for SMB and RDP..."
nmap -iL /tmp/arp-scan -Pn -n -v -p135,445,139,3389|grep Discovered|sed -E 's/.+ ([0-9]+)\/[^0-9\.]+([0-9\.]+)/\2:\1/g' 2>/dev/null | tee /tmp/smb-rdp-scan
cat /tmp/smb-rdp-scan | grep -E '135|445|139' | cut -d ':' -f1 |sort -u|shuf > /tmp/smb-hosts
echo ''
while read smbhost; do
echo "smb://$smbhost:" >> /tmp/smb-version
echo "smb://$smbhost:"
smbclient //$smbhost/ipc\$ -N -c "q" -g -L 2> >(tee -a /tmp/smb-version)
done < /tmp/smb-hosts

echo -e "\nFound SMB Hosts:"
cat /tmp/smb-hosts
echo
echo -e "\nFound RDP Hosts:"
cat /tmp/smb-rdp-scan|grep 3389
echo
